### ISSUE TITLE
2 broken links in the introduction and prerequisites section of RHSCL

### ISSUE THREAD

**Issue by omajid** [redhat-developer/developers.redhat.com#1366]
http://developers.redhat.com/products/softwarecollections/get-started-rhel7-python/#PrerequisitesSection contains 3 links:

- "registering and downloading" points to http://developers.redhat.com/products/softwarecollections/get-started-rhel7-python/#%7Bsite.download_manager_base_url%7D/download-manager/link/1350474
- "developers.redhat.com" points to http://developers.redhat.com/products/softwarecollections/get-started-rhel7-python/#%7Bsite.base_url%7D/
- "Troubleshooting and FAQ"

The first two are broken. I suspect the same is true for all RHSCL pages.

**Comment by rctrh** [comment]
Ok, thanks. I'll look into that.  There is some macro slight of hand there that was working when deployed and now seems to have gotten broken as the page URL is being prepended, but shouldn't be.    Same issue will affect all of these pages.

**Comment by rctrh** [comment]
PR #1371  was merged.  This issue can be closed.

**Comment by omajid** [comment]
Looks fixed to me. Thanks!
