### ISSUE TITLE
Reduce/Eliminate calls to JSDelivr via Bootstrap theme

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3008]
### Description

There are scenarios now where an absurd number of calls are made to the JSDelivr CDN by the Bootstrap theme. In one stack trace in New Relic, 619 calls are made to JSDelivr to load the /admin/content route.

### Acceptance Criteria

* Ensure Beryllium isn't trying to use a CDN for anything
* Update the Bootstrap theme to the latest version to see if that resolves this issue
* Determine if we can just disable the CDN feature from the Bootstrap theme entirely. Ensure that this doesn't break anything.

**Comment by jordanpagewhite** [comment]
I tried disabling the CDN on the Bootstrap theme's setting page (locally), but the method JsDelivr::processDefinition() is still executed for some reason even though I cannot figure out _why_ you would want that code executed if you aren't pulling from a CDN. I entirely commented out the method, and I noticed an improvement in the load time of a few admin pages I tried.

More testing and investigation should be done here, but this verifies that the easiest possible solution of just setting the Bootstrap theme config to 'no CDN' does not resolve this issue.

**Comment by jordanpagewhite** [comment]
*Commented out body of ProviderManager::processDefinition()*
/admin/content
no cache, clear Drupal cache before each request and hard refresh in Chrome

Load time, TTFB
------------------
5.43, 5.42
4.88, 4.86
5.20, 5.17
5.05, 5.03
5.05, 5.01

*ProviderManager::processDefinition()*
/admin/content
no cache, clear Drupal cache before each request and hard refresh in Chrome

Load time, TTFB
------------------
7.89, 7.85
7.32, 7.29
7.18, 7.14
6.96, 6.92
7.71, 7.69

**Comment by jordanpagewhite** [comment]
*Next steps*

* Determine how we can not execute the code in the Bootstrap theme that made any external calls or unnecessarily caches responses. We do not need to load the actual Bootstrap assets in this theme, and we definitely should not be making any network calls to fetch them nor cache those responses.

**Comment by robpblake** [comment]
This is a priority in my mind. We can throw all the caching in the world at Drupal, but it's the external network calls that are killing performance.

**Comment by jordanpagewhite** [comment]
#3010

**Comment by robpblake** [comment]
#3010 Is merged and will go out tomorrow morning.
