### ISSUE TITLE
Create a new base theme consuming the new rhd-frontend assets

### ISSUE THREAD

**Issue by fearlsgroove** [redhat-developer/developers.redhat.com#3012]
- [ ] Create a base theme
- [ ] Set the new base theme as the default
- [ ] Uninstall `rhdp` theme
- [ ] Pull in the latest `master` commit rhd-frontend repo
- [ ] Include the `rhd-frontend` CSS and JS by building out the `dist` assets in the `docker-compose` build process
- [ ] Create a way for a developer to manually build the `dist` assets to the `rhd-frontend` package in the container from their local machine
- [ ] Get it building in stage

**Comment by jordanpagewhite** [comment]
Work in progress: https://github.com/redhat-developer/developers.redhat.com/pull/3015

**Comment by jordanpagewhite** [comment]
This can be closed as #3015 has been merged and deployed to the Dev environment
