### ISSUE TITLE
Port masthead styles & markup

### ISSUE THREAD

**Issue by fearlsgroove** [redhat-developer/developers.redhat.com#3013]
Port styles from the legacy theme for masthead including 
- [ ] Universal header
- [ ] Logo
- [ ] Secondary nav (events, training, help products)
- [ ] masthead search
- [ ] main navigation + all topics

**Comment by jordanpagewhite** [comment]
Blocked by https://github.com/redhat-developer/rhd-frontend/issues/261

**Comment by jordanpagewhite** [comment]
Unblocked by https://github.com/redhat-developer/rhd-frontend/pull/312
