### ISSUE TITLE
Normalize and type styles

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3021]
### Acceptance Criteria

- [x] We have all styles in place for typography, and these styles are all demonstrated on some page in Drupal
- [x] We have some CSS in place to normalize
- [x] Create a demo page that includes a set of basic html elements (h1-6, p, ul/ol/li, etc)
- [x] Make sure fonts are included and working (overpass etc)

**Comment by jordanpagewhite** [comment]
https://github.com/redhat-developer/rhd-frontend/issues/87

**Comment by rogeralloymagnetic** [comment]
See my last comment here: https://github.com/redhat-developer/rhd-frontend/pull/215

**Comment by rogeralloymagnetic** [comment]
Closed with: https://github.com/redhat-developer/developers.redhat.com/pull/3095
