### ISSUE TITLE
MetatagToken::generateRawElements takes nearly 3 seconds with a lot of calls to content_moderation_edit_notify_tokens

### ISSUE THREAD

**Issue by robpblake** [redhat-developer/developers.redhat.com#3029]
<img width="1293" alt="Screenshot 2019-08-29 at 13 31 57" src="https://user-images.githubusercontent.com/1170393/63941858-6023a580-ca64-11e9-9076-a28b6c5ffe8a.png">

In some requests, we're spending nearly 3 seconds executing the MetatagToken::generateRawElements method with most of that time being spent making calls to `content_moderation_edit_notify_tokens`.

We need to work out what is going on here and see if we can prevent this.

**Comment by robpblake** [comment]
@jordanpagewhite I noticed this today whilst going through some of the traces in New Relic to try and understand where Drupal is spending time. Not sure if you have any ideas as to what it might be trying to do at this point?

cheers,

Rob

**Comment by robpblake** [comment]
@rogeralloymagnetic You seem to know your way around the cotent_moderation_notify module. Any ideas what  might be going on here to cause such slow render times?

**Comment by rogeralloymagnetic** [comment]
@robpblake I don't know off the top of my head, but I can take a look early next week if you want.

**Comment by robpblake** [comment]
@rogeralloymagnetic If you have some time it could be a useful one for us to get a feel for what is going on. I don't want it to distract from the new theming work, so only if you have time.

cheers,

Rob
