### ISSUE TITLE
Cannot edit files in ./web/modules/contrib/

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3033]
Hey Rob. The user that I log into the container with, when I run `bash ./dev/run-drupal-connect.sh`, does not have permission to edit files in `./web/modules/contrib`. I need access to do this to debug contrib modules. Am I overlooking an obvious step or forgetting something? I am not sure if perhaps this changed at some point. I seem to remember being able to do this in the past. Anyway, if something has changed, I am just creating this issue so that we can either resolve it (if necessary) or document the new step(s) required to modify contrib files. Thanks.

**Comment by robpblake** [comment]
@jordanpagewhite Yeah this will yet another permissions issue I've introduced by updating the user that the container runs as for local development.

I'll try and get around to this today.

cheers,

Rob
