### ISSUE TITLE
Move Composer patch files to local filesystem

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3039]
We need to move our patch files, and the references to the patches in composer.json/composer.lock, to the local filesystem. The network calls fail sometimes in our build process, which causes the entire build to fail.

### Acceptance Criteria

* For any patch that currently depends on a network call to some other site i.e. drupal.org, download the .patch file and place it in the /patches/[module_slug] directory.
  * If a [module_slug] directory does not exist for a given module (or core), create one.
* All patches defined in composer.json should use relative file paths (not network calls to drupal.org or githubusercontent.com etc.)

**Comment by jordanpagewhite** [comment]
How timely! I just ran into this issue as I was creating the issue.

Ex.

```
   Could not apply patch! Skipping. The error was: The "https://www.drupal.org/files/issues/2019-06-21/2174633-309.patch " file could not be downloaded (HTTP/1.1 500 Domain Not Found)
```

**Comment by jordanpagewhite** [comment]
https://github.com/redhat-developer/developers.redhat.com/pull/3040

**Comment by robpblake** [comment]
No longer required as my work to fix the issues with the proxy and also to make use use the Nexus NPM registry seems to have resolved the instability here.
