### ISSUE TITLE
Manage Docker Image size increases as part of surge work

### ISSUE THREAD

**Issue by robpblake** [redhat-developer/developers.redhat.com#3042]
We need to keep an eye on the impact of the `surge` work on the size of our Docker image. We're currently sat on a 15% image size increase:

![Screen Shot 2019-09-05 at 11 11 55](https://user-images.githubusercontent.com/1170393/64333240-0f64fd00-cfce-11e9-8b61-50ae94b744cb.png)

**Comment by robpblake** [comment]
`preview-3041` is a pre-surge image at 514.1MB, `preview-3015` is the current HEAD of `surge` development.

**Comment by jordanpagewhite** [comment]
Hey @robpblake Are there any actionable item(s) we can define on this ticket? I am not trying to diminish the importance of keeping the image as small as possible, but I cannot think of any changes we can (reasonably) make right now to reduce the size. You and I discussed the goal of eventually removing the `rhdp` theme, in favor of the single `rhdp2` theme, which will be coming (at some point) in the future. Are there other things you have on your mind?

**Comment by robpblake** [comment]
@jordanpagewhite Immediate wins I can see are:

* As you say, removing `rhdp` theme by probably just collapsing it into `rhdp2` for now
* Fixing the `rhd-frontend` build process so that the assets do not have to be in the Drupal container

cheers,

Rob
