### ISSUE TITLE
Fix broken favicon file paths

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3045]
There are many favicon file paths that are broken because we are deleting the rhd-frontend directory at the end of our rhdp2 theme build process in Dockerfile.mp

### Acceptance Criteria

* We've pulled the assets we need out of rhd-frontend before we delete the directory, and we update file references pointing to the proper place in the filesystem

**Comment by jordanpagewhite** [comment]
#3044

**Comment by robpblake** [comment]
@jordanpagewhite Can you tell me what is referencing the favicons please?
