### ISSUE TITLE
Featured Resources

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3058]
FE Ticket: (card) https://github.com/redhat-developer/rhd-frontend/pull/124/files

This might not require any _extra_ effort beyond the styling of the individual components that are used in this assembly type.

Screenshot:

<img width="1223" alt="Screen Shot 2019-09-09 at 12 46 51 PM" src="https://user-images.githubusercontent.com/7155034/64561610-0347ab00-d300-11e9-8fb4-02f073e4a623.png">

**Comment by jordanpagewhite** [comment]
### Remaining work

- Resolve the issue with the content image aspect ratio

**Comment by jordanpagewhite** [comment]
@sjcox-rh I believe that the remaining work on this issue (the content image aspect ratio) is now resolved by changes made in the `rhd-frontend` repo. Can you confirm on pages like this? https://developers.dev.redhat.com/topics/microservices/ Ebooks and Cheat Sheet cards

**Comment by sjcox-rh** [comment]
@jordanpagewhite yup the image aspect ratio is fixed! The only other change I see with this card is to add padding above the image. Right now it looks like there is none. There should be 16px above the image to match the bottom 16px padding.

Hope that is a quick fix!

**Comment by jordanpagewhite** [comment]
@sjcox-rh Great, thank you. This issue https://github.com/redhat-developer/rhd-frontend/issues/229 in the `rhd-frontend` project will track that issue you reported in you comment above and all outstanding issue with spacing within a Card component. Thanks again.

**Comment by jordanpagewhite** [comment]
Since this is just a CSS change in the FE repo, there is no more work to do here and the issue is tracked in the FE repo, so this can be closed.
