### ISSUE TITLE
Events Hero

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3099]
FE issue: https://github.com/redhat-developer/rhd-frontend/issues/169

Marvel: https://marvelapp.com/c6c454h/screen/61838131 (screen 8)

Estimate: 3

**Comment by jordanpagewhite** [comment]
https://github.com/redhat-developer/rhd-frontend/pull/288 In Review in FE repo

**Comment by jordanpagewhite** [comment]
https://github.com/redhat-developer/rhd-frontend/pull/288 was merged, so this is unblocked

**Comment by jordanpagewhite** [comment]
Estimate: 3

**Comment by rogeralloymagnetic** [comment]
PR: https://github.com/redhat-developer/developers.redhat.com/pull/3173
