### ISSUE TITLE
Update Visual Styles for Product Download Hero and Product Try-It Hero.

### ISSUE THREAD

**Issue by rogeralloymagnetic** [redhat-developer/developers.redhat.com#3103]
Currently, the rhd-frontend repo uses the following classes for the parent container:
```
dark
light
centered
image-first
slim
```

But, the developers.redhat.com repo uses:
```
product-hero--dark
product-hero--dark-centered
product-hero--light
product-hero--light-centered
product-hero--slim
```

I've updated the developers.redhat.com repo to include both and labeled the old ones as `(deprecated)`

**Comment by jordanpagewhite** [comment]
This will be resolved by #3148
