### ISSUE TITLE
Bug: Curated Link assembly graceful degradation

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3110]
When _only_ links are provided in the Curated Links assembly, those links should 'expand' into columns to fill the space. See this example

https://developers.redhat.com/topics/

https://developers.dev.redhat.com/topics/

**Comment by sjcox-rh** [comment]
@jordanpagewhite Also broken on the [rhel 8](https://developers.redhat.com/rhel8/) page.

The display mode and visual style is not working to display this assembly into two rows. 

By default this should be one column but fill up width of screen.

**Comment by joeschram** [comment]
And broken on the [/topics](https://developers.redhat.com/topics) page too: 😭 

<img width="1399" alt="Screen Shot 2019-10-16 at 9 09 58 PM" src="https://user-images.githubusercontent.com/5090034/66969871-57f5e880-f059-11e9-9336-0e37e6cc5fd8.png">

**Comment by rogeralloymagnetic** [comment]
"hotfix" PR: https://github.com/redhat-developer/developers.redhat.com/pull/3360

* As mentioned in the PR, the content model on this assembly needs to be revisited with UX and FE. 
* There are currently Visual Styles and Display Modes that were created pre-Surge that don't seem to be working or being used correctly.
* Most also do not have references in FE.

**Comment by rogeralloymagnetic** [comment]
Follow-up issue created here: https://github.com/redhat-developer/developers.redhat.com/issues/3361
