### ISSUE TITLE
Remove topic page display NOT view_topics

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3119]
We have a `view_topics` that display here: `/topics` and a deprecated `topic` with an unpublished `Page` display. We can remove/delete that `Page` display, but we should keep the `Feed` display, as the RSS Feed is used.

**Comment by rogeralloymagnetic** [comment]
PR: https://github.com/redhat-developer/developers.redhat.com/pull/3353
