### ISSUE TITLE
Featured Evangelists

### ISSUE THREAD

**Issue by rogeralloymagnetic** [redhat-developer/developers.redhat.com#3121]
/about/

Estimate: 3

**Comment by jordanpagewhite** [comment]
https://github.com/redhat-developer/rhd-frontend/pull/293 In Review in FE repo

**Comment by jordanpagewhite** [comment]
https://github.com/redhat-developer/rhd-frontend/pull/293 has been merged. This is now unblocked.

**Comment by jordanpagewhite** [comment]
Closed by #3167
