### ISSUE TITLE
FOOTER: `Report a website issue` link broken. Looks like a JS issue.

### ISSUE THREAD

**Issue by rogeralloymagnetic** [redhat-developer/developers.redhat.com#3122]
See site footer

Estimate: 3 (assuming current ignorance of JIRA widget embed)

**Comment by jordanpagewhite** [comment]
This is blocked by https://github.com/redhat-developer/rhd-frontend/issues/309 and should be entirely resolved once https://github.com/redhat-developer/rhd-frontend/issues/309 is done.

**Comment by jordanpagewhite** [comment]
I just tested this out since #3166 was merged, and the Report a website issue link/iframe is working now 👍
