### ISSUE TITLE
Migrate /books from Rich Text to a View

### ISSUE THREAD

**Issue by rogeralloymagnetic** [redhat-developer/developers.redhat.com#3124]
/books is all in rich text in a deprecated page template, and using Foundation layout classes. This page/route needs to be updated to use a Drupal View for formatting, display and filtering the content.

Drupal estimate: 8

**Comment by jordanpagewhite** [comment]
On Prod /books redirects to /search/?s=most-recent&f=sys_type~book , so this is not a requirement of this quarter and possibly not a requirement at all. It seems that /books might be phased out.

**Comment by jordanpagewhite** [comment]
We need to confirm with Joe whether or not this is a requirement before any work starts on this issue.
