### ISSUE TITLE
Product Pages

### ISSUE THREAD

**Issue by rogeralloymagnetic** [redhat-developer/developers.redhat.com#3130]
`modules/custom/rhd_common/templates/product-pages.html.twig`

/products/rhamt/hello-world#fndtn-macos

**Comment by jordanpagewhite** [comment]
This issue might be entirely resolved by this PR: https://github.com/redhat-developer/developers.redhat.com/pull/3105

We want to be able to load the old, paragraphs-based Product pages using the `rhdp` theme while still loading the new, assembly-based Product pages using the `rhdp2` theme.

**Comment by jordanpagewhite** [comment]
Closed by #3159
