### ISSUE TITLE
CONTENT: Rich text content using .columns will need to be updated to use new grid system.

### ISSUE THREAD

**Issue by rogeralloymagnetic** [redhat-developer/developers.redhat.com#3137]
Examples:
- Homepage Hero
- /topics/containers/

Drupal estimate: 0
Content estimate: ?

**Comment by jordanpagewhite** [comment]
See complete list of assemblies and nodes here: https://docs.google.com/spreadsheets/d/1SC5lhDA-C9Uvj1ZRIAty7a0Qzker3xnksPU1JzjtchE/edit#gid=1259823328

@joeschram @sjcox-rh @gdoyle1

**Comment by jordanpagewhite** [comment]
This will be tracked and closed by https://github.com/redhat-developer/rhd-frontend/issues/302
