### ISSUE TITLE
Add missing Drupal Field to Event Hero Assembly

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-developer/developers.redhat.com#3149]
### Acceptance Criteria

- The Sidebar Link should display to the right of the Sign Up CTA button within the main column in all scenarios

### Screenshot example

Please make yours look better. Use the Product heroes as references.

<img width="1273" alt="Screen Shot 2019-10-04 at 9 35 09 AM" src="https://user-images.githubusercontent.com/7155034/66224296-6243da00-e68a-11e9-8afa-ab73e9c7f274.png">

### Original report (for posterity)

When using this assembly and adding only one event, you do not have the option to add a secondary CTA, the field is missing.

However, when adding in two or three events, you get the option for a secondary CTA.

The need for a secondary CTA still applies for only one event so just requesting to add that option.

**Comment by jordanpagewhite** [comment]
I am going to consider this blocked by the same blocker on #3099 because it makes sense to work on this at the same time  as #3099

**Comment by rogeralloymagnetic** [comment]
PR: https://github.com/redhat-developer/developers.redhat.com/pull/3173
