### ISSUE TITLE
Dynamic Form actions are not being captured properly across the site

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3174]
We are not capturing Dynamic Form actions in Adobe Analytics on developers.redhat.com.  The digitalData.event that DyFo fires is not firing on our pages. 

Check out these two pages to see what we are expecting to fire for DyFo:
https://www.redhat.com/en/contact
https://www.ansible.com/contact-us

Adobe Tag manager uses this event to fire off the different beacons that capture the data.

Marcia Corman from MarketingOps confirmed for us that the iframe is behind this issue. As an example, the Dynamic Form on the RHD Contact sales page is within an iframe. The digitalData object is pushing the data layer events as expected, but it is populating within the iframe instead of the parent page. If DyFo is to remain within an iframe, the iframe code will need to post the event to the parent page where the parent page will then receive that message and push the corresponding event to the data layer. 

This is the page with Dynamic Form:  https://developers.redhat.com/contact-sales. We are not capturing any tracking other than parent page view so we can't capture how many times this form was submitted in Adobe Analytics.

This issue prevents us from tracking interactions with Dynamic Form on RHD; we are still tracking form completes on the backend but we can't track the flow of visitors from our pages to form complete in Adobe Analytics. This is an important business requirement for us; for example, we cannot track our Contact Us form to complete in Adobe due to the current iframe method used to deploy Dynamic Form.

@KamiQuasi 's theory is that we'll need to look more into the Drupal side of how we're embedding the Eloqua forms onto pages. He believes that the original implementation of this was done based on his old DevNation Live setup, which may be a bit dated at this point.

**Comment by clt2rdu** [comment]
@joeschram , I wanted to check on the status of this issue and what sprint you think it will be added to?  Thanks!
