### ISSUE TITLE
WAS/WCAG Accessibility Audit

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3187]
Now that we're on PF4 Core elements, how does RHD measure up for [WAS](https://accessible.org/Web-Accessibility-Standards-WAS-2.pdf) or [WCAG compliance](https://www.w3.org/WAI/WCAG21/quickref/)?

Quick [explainer article](https://medium.com/@krisrivenburgh/the-ada-checklist-website-compliance-guidelines-for-2019-in-plain-english-123c1d58fad9).

Do we need to look at a tool like [Accessibe](https://accessibe.com/) to audit our site?

**Comment by robpblake** [comment]
@joeschram I'd highly recommend that you talk to JP Sherman from the Customer Portal team about DeepCrawl as it may be able to do this for you in addition to a whole bunch of other stuff e.g. broken link scanning, SEO optimisation recommendations.

Customer Portal are already using DeepCrawl, so there would be benefits from consolidating around a single technology platform, particularly if that team already has expertise in it.

cheers,

Rob

**Comment by mindreeper2420** [comment]
On PatternFly, we use a combination of the [aXe: The Accessibility Engine](https://www.deque.com/axe/) plugin, JAWS for screen readers and the [WAVE browser extension](https://wave.webaim.org/extension/).

We post the PatternFly Accessibility Guidelines as well, for those that use PatternFly without directly using the React library (which has a lot of accessibility built into the components).

[PatternFly Accessibility Guide](https://www.patternfly.org/v4/get-started/accessibility-guide)

I'd be happy to run through the high traffic pages with the plugins to get a baseline, while automation is added.
