### ISSUE TITLE
/topics/service-mesh

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-developer/developers.redhat.com#3208]
- [x] Check overall page rendering: desktop, tablet, mobile
- [x] Are comments showing in the dynamic content assemblies?
- [x] Make sure all dynamic assemblies have a CTA at the bottom that links out to more content in the Wordpress paginator with that same set of tags (see example at bottom of on /topics/enterprise-java)
- [x] Check Rich Text Assemblies (RTAs) on desktop, tablet, mobile: do they need to be rebuilt? If so, apply cookbook PFE layouts
- [x] Check card displays: desktop, tablet, mobile
- [ ] Check if images or titles on the cards need to be adjusted back in the originating node (Wordpress or Drupal)—for example, an article's image is badly formatted, or is missing; article title is too long or too short; video description is too long.
- [x] Is there an opportunity to *add* a card or list item, mainly because the new styling has tightened up that area—revealing a visual gap? (e.g. 3-up horizontal card list that now appears to be missing a 4th card)
- [x] Swap out any old background image (e.g. blue "morse code" on Video Hero) to new RHD "stark red, dark, or light" backgrounds
- [x] Check the spacing between assemblies, check visual styles applied, all up and down the page; remove non-breaking spaces from RTAs where we were hacking for vertical height before
- [x] Make any styling changes necessary

**Comment by joeschram** [comment]
Add back these articles when the two Coolstore articles can have proper hero images added:

[Istio: It makes a mesh of things](https://developers.redhat.com/blog/2018/03/06/introduction-istio-makes-mesh-things/)
[Istio Service Mesh Blog Series Recap](https://developers.redhat.com/blog/2018/05/07/istio-service-mesh-blog-series-recap/)
[Bringing Coolstore Microservices to the Service Mesh: Part 1 - Exploring Auto-injection](https://developers.redhat.com/blog/2018/04/05/coolstore-microservices-service-mesh-part-1-exploring-auto-injection/)
[Bringing Coolstore Microservices to the Service Mesh: Part 2--Manual Injection](https://developers.redhat.com/blog/2018/04/12/bringing-coolstore-microservices-to-the-service-mesh-part-2-manual-injection/)
