### ISSUE TITLE
Improve animation smoothing on card hover state reveal

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3220]
This animation on-hover needs to feel smoother, should indicate to the user that the reveal is intentional (vs. a rendering glitch).

Maybe slowing it down a hair would do that?

And…should we indicate in some way to the user that the card title has more text to be unrolled?

![2019-10-15 14 41 51](https://user-images.githubusercontent.com/5090034/66859823-0155b500-ef5a-11e9-86f0-3979fe00eacc.gif)

**Comment by jordanpagewhite** [comment]
@joeschram I've created this issue in the FE repo. I will close this issue in the Drupal repo, and we will track progress in this issue: https://github.com/redhat-developer/rhd-frontend/issues/387 in the rhd-frontend repo. Thanks.
