### ISSUE TITLE
Events Hero sidebar_link_title arrow showing as blue, not black on .light background

### ISSUE THREAD

**Issue by rogeralloymagnetic** [redhat-developer/developers.redhat.com#3238]
![Screen Shot 2019-10-15 at 9 49 44 AM](https://user-images.githubusercontent.com/41014351/66864909-72459e80-ef53-11e9-9338-8c37a2e3b1da.png)

**Comment by mindreeper2420** [comment]
@rogeralloymagnetic I'm not seeing this issue when viewing just the pure component from the rhd-repo (running locally). 
<img width="722" alt="Screen Shot 2019-12-09 at 10 43 21 AM" src="https://user-images.githubusercontent.com/4032718/70449873-ba270480-1a70-11ea-993d-78e92cf421b3.png">

**Comment by rogeralloymagnetic** [comment]
@mindreeper2420 Good to know. Looks like we'll need to move this into a Drupal environment to continue testing/fixing. Let me know if we need to reassign it, or if you can take a look in a local Drupal instance first.

**Comment by mindreeper2420** [comment]
@rogeralloymagnetic I'll unassign myself from this, as I'm still having issues with my local Drupal environment.
