### ISSUE TITLE
Title on Rich Text Columns assembly type

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3246]
<img width="1620" alt="Screen Shot 2019-10-15 at 1 15 08 PM" src="https://user-images.githubusercontent.com/7155034/66866329-e8470700-ef4d-11e9-9776-3c3c339a9ce9.png">

**Comment by rogeralloymagnetic** [comment]
@jordanpagewhite I don't see what the difference is between:
Live Code - https://developers.redhat.com/products/openjdk/overview
Design - https://redhat-developer.github.io/rhd-frontend/components/rich_text_columns/

I don't know what the action item is here.

**Comment by jordanpagewhite** [comment]
If I recall correctly, I quickly created this ticket leading up to our launch last week. Unfortunately, I didn't do a good job of describing this issue here. I believe that @sjcox-rh pointed out the spacing between the title of this assembly and the content was incorrect. That issue was resolved by Matt Moen's big spacing PR leading up to the launch.

@sjcox-rh Do you happen to remember if that is correct? I will close that now with the assumption that my memory is serving me well. If you remember some other issue(s) that remain unaddressed, please just let me know here and we'll open the issue
