### ISSUE TITLE
Rendering on /products is broken

### ISSUE THREAD

**Issue by robpblake** [redhat-developer/developers.redhat.com#3251]
The rendering on the `/products` page is broken. It's showing what I think is Twig mark-up and not the usual icons.

![Screen Shot 2019-10-16 at 15 26 16](https://user-images.githubusercontent.com/1170393/66928500-63c9b680-f029-11e9-8341-ba547a22be88.png)

**Comment by jordanpagewhite** [comment]
@robpblake This is working as we expect. This is the `assembly-type-product_categories` assembly type. It is only used on this one page. Once this code deploys to Prod, we will delete this assembly from this page, and we will no longer be using the product categories assembly type.
