### ISSUE TITLE
Add vertical padding after last footer column

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3255]
Last footer content column does not have padding after it when viewed on mobile. Padding after *Communicate* column does not match padding after *Quicklinks* column. 

<img width="816" alt="Screen Shot 2019-10-16 at 2 06 51 PM" src="https://user-images.githubusercontent.com/5090034/66946251-8acebb00-f01e-11e9-99cf-57924274bce7.png">

**Comment by staceymosier** [comment]
This has been entered into JIRA - https://projects.engineering.redhat.com/browse/RHDX-122
