### ISSUE TITLE
Call to Action Assembly button fix

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-developer/developers.redhat.com#3258]
When using the call to action assembly, under the CTA link assembly, you have two fields to input the link AND change the text link. The field to change the text link does not work currently. 

I filled out the field to have the cta link say "Start lesson" 
<img width="1315" alt="Screen Shot 2019-10-16 at 12 39 12 PM" src="https://user-images.githubusercontent.com/16257540/66953633-c4e68f80-f013-11e9-8ab4-2380ac15517f.png">

When published, the button was still showing the default cta text of "Learn More"
<img width="1055" alt="Screen Shot 2019-10-16 at 12 39 56 PM" src="https://user-images.githubusercontent.com/16257540/66953681-d5970580-f013-11e9-87d3-283bc1daff96.png">

**Comment by sjcox-rh** [comment]
Linked to another issue @svalverdetwiggs created #3297

**Comment by rogeralloymagnetic** [comment]
PR: https://github.com/redhat-developer/developers.redhat.com/pull/3302
