### ISSUE TITLE
Additional use case for global assembly padding

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-developer/developers.redhat.com#3260]
We need to add another use case for global assembly padding. If an assembly is used at the top of the page (in position 0) and is using a background, then there should be no padding above it. 

Currently we are coming across this issue across the site where there is space between the topic nav and the first assembly.

<img width="1530" alt="Screen Shot 2019-10-16 at 12 48 21 PM" src="https://user-images.githubusercontent.com/16257540/66953905-3292bb80-f014-11e9-8a34-a9ce17d89da6.png">

**Comment by jordanpagewhite** [comment]
Closing to move this issue to the FE repo: https://github.com/redhat-developer/rhd-frontend/issues/403
