### ISSUE TITLE
(3) Product try-it hero is defaulting to dark-slim visual style 

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/developers.redhat.com#3262]
Estimate: 3

The dark, slim visual style is default for produc try-it hero even when I try to override it to have no visual style and include a background image.

Was appearing on products/codeready-containers/overview

### Acceptance Criteria
1. Default visual output is well-defined from UX
2. Assignee implements that default  visual output without causing a regression for any visual styles

**Comment by rogeralloymagnetic** [comment]
@gdoyle1 Can you confirm this issue still exists? I'm not able to replicate and am wondering if it may have already been resolved in another issue.

**Comment by gdoyle1** [comment]
@rogeralloymagnetic @jordanpagewhite This is actually no longer happening! I just tested it and it was working fine

**Comment by rogeralloymagnetic** [comment]
Great, closing this issue :)
