### ISSUE TITLE
Inline code is not formatting as monospace in WordPress

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3263]
Estimate: 1

See: https://developers.redhat.com/blog/2019/10/14/introducing-debuginfod-the-elfutils-debuginfo-server/

Looks like it is a regression from today's merge

![Screen Shot 2019-10-16 at 4 32 49 PM](https://user-images.githubusercontent.com/5090034/66956797-076b9480-f033-11e9-8823-6214669c780b.png)

**Comment by rendsley** [comment]
Code tags aren't working to make text monospace. 
Looks like pre tags still work though.
