### ISSUE TITLE
Fix forms and all RTAs on OpenJDK bonus pages

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3264]
https://developers.redhat.com/oraclejdkalternative/
AND
https://developers.redhat.com/oracle-java-support-openjdk/

### Alternatives Page

- Rebuild the three RTAs

<img width="1440" alt="Screen Shot 2019-10-16 at 4 45 14 PM" src="https://user-images.githubusercontent.com/5090034/66957625-93ca8700-f034-11e9-81ad-d607f58a8e67.png">

<img width="1428" alt="Screen Shot 2019-10-16 at 4 45 28 PM" src="https://user-images.githubusercontent.com/5090034/66957632-975e0e00-f034-11e9-92f8-594b9b9cd312.png">

<img width="1432" alt="Screen Shot 2019-10-16 at 4 45 36 PM" src="https://user-images.githubusercontent.com/5090034/66957639-9b8a2b80-f034-11e9-994c-d41bc376b62f.png">

- Figure out what's wrong with the inserted Eloqua form; crib the one from the Oracle Java Support page below if need be

<img width="434" alt="Screen Shot 2019-10-16 at 4 45 49 PM" src="https://user-images.githubusercontent.com/5090034/66957664-a349d000-f034-11e9-922f-e38381d5f0ec.png">

### Oracle Java Support Page

Improve these RTAs:

(better text)

<img width="1228" alt="Screen Shot 2019-10-16 at 4 52 31 PM" src="https://user-images.githubusercontent.com/5090034/66958125-882b9000-f035-11e9-8b66-4a4cd55f1a4a.png">

(this one needs better type and mobile sizing, icon wrapping)

<img width="1143" alt="Screen Shot 2019-10-16 at 4 52 35 PM" src="https://user-images.githubusercontent.com/5090034/66958138-8cf04400-f035-11e9-825d-33f40703acd5.png">

(new background)

<img width="1324" alt="Screen Shot 2019-10-16 at 4 52 40 PM" src="https://user-images.githubusercontent.com/5090034/66958146-911c6180-f035-11e9-82c2-76ab428dae46.png">

**This form is better than the one above…maybe steal it?**

<img width="959" alt="Screen Shot 2019-10-16 at 4 52 53 PM" src="https://user-images.githubusercontent.com/5090034/66958270-d2147600-f035-11e9-9835-baf37f8ee42f.png">

**Comment by gdoyle1** [comment]
https://developers.redhat.com/oraclejdkalternative/ 
fixed the documentation and support assemblies
