### ISSUE TITLE
Assembly title is not rendering on-page for Curated Links assembly

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3270]
- Go to /openshift in your browser like a visitor would
- Open https://developers.redhat.com/openshift/edit in your signed-in Drupal authoring session via a different browser 
- Notice that on-page Titles for the Curated Link assemblies do not display on page (they did before the merge)

**Comment by rogeralloymagnetic** [comment]
PR: https://github.com/redhat-developer/developers.redhat.com/pull/3354
