### ISSUE TITLE
Jump to Nav Assembly button display/stacking is broken on Mobile and Tablet

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-developer/developers.redhat.com#3271]
Need to update to use same button spacing logic that @alistairmc put in place for buttons within an assembly.

<img width="613" alt="Screen Shot 2019-10-16 at 3 49 59 PM" src="https://user-images.githubusercontent.com/16257540/66965234-cfae1e00-f02d-11e9-9657-46f9cc9a3490.png">

**Comment by rogeralloymagnetic** [comment]
Waiting on FE ticket referenced above. Not sure there will be any Drupal actions needed on this.
