### ISSUE TITLE
Fix New Relic monitoring scripts to properly display status for RHD Login on https://status.redhat.com

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3272]
I think this is a false positive due to our merge changes.

**Comment by joeschram** [comment]
Best I can tell, login works—we should make sure New Relic is properly detecting our status. I will test logging in with throwaway account tonight, will also test creating an account from scratch. I'll update this ticket after.

<img width="907" alt="Screen Shot 2019-10-16 at 7 03 29 PM" src="https://user-images.githubusercontent.com/5090034/66965561-19a3fd80-f048-11e9-9d1d-82f54f7cd6a9.png">

**Comment by joeschram** [comment]
@robpblake I was able to sign in as myself (jschram) and download [OCP 3.10 for linux](https://developers.redhat.com/products/openshift/download) and [RHEL 7.3 boot iso.](https://developers.redhat.com/products/rhel/download)

**Comment by robpblake** [comment]
`/login` has an infinite re-direct loop if you visit it and then login, so technically the New Relic check failure was valid.

I have no idea how this has ever worked. I've fixed the New Relic check to visit the home page and click on the `Log In` button which is a much better option, but we need to resolve the `/login` redirect loop incase of any existing links in the wild using that reference.
