### ISSUE TITLE
/welcome

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3276]
- [x] Check overall page rendering: desktop, tablet, mobile
- [x] Are comments showing in the dynamic content assemblies? **there isn't one**
- [x] Make sure all dynamic assemblies have a CTA at the bottom that links out to more content in the Wordpress paginator with that same set of tags (see example at bottom of on /topics/enterprise-java)
- [x] Check Rich Text Assemblies (RTAs) on desktop, tablet, mobile: do they need to be rebuilt? If so, apply cookbook PFE layouts
- [x] Check card displays: desktop, tablet, mobile
- [x] Check if images or titles on the cards need to be adjusted back in the originating node (Wordpress or Drupal)—for example, an article's image is badly formatted, or is missing; article title is too long or too short; video description is too long.
- [x] Is there an opportunity to *add* a card or list item, mainly because the new styling has tightened up that area—revealing a visual gap? (e.g. 3-up horizontal card list that now appears to be missing a 4th card) **could add another katacoda course**
- [x] Swap out background image from old style (e.g. blue "morse code" on Video Hero) to new RHD "stark red" backgrounds
- [x] Check the spacing between assemblies, check visual styles applied, all up and down the page; remove non-breaking spaces from RTAs where we were hacking for vertical height before

**Comment by gdoyle1** [comment]
- [ ] Rich text social icons assembly
- [ ] Rich text with image resources assembly
- [ ] Advance your career

**Comment by gdoyle1** [comment]
Waiting on a pagination bug fix to get the margins right. @joeschram There are only 3 cards in the openshift courses if you want to add another!

**Comment by sjcox-rh** [comment]
@gdoyle1 I added another katacoda course and updated the grid on the last assembly since for some reason it wasnt working.  Also updated some bg's!

**Comment by gdoyle1** [comment]
Thank you!! @sjcox-rh The only thing we'll  be waiting on then is the collection pagination fix.
