### ISSUE TITLE
Extend max text length for Events by at least 10 characters

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3277]
DevNation Live webinars are now called DevNation Tech Talks. That name change has ruined our ability to add good descriptions to the Event entries in Drupal because we only have 45 char to do it! 😄

**Comment by joeschram** [comment]
<img width="1408" alt="Screen Shot 2019-10-16 at 11 07 56 PM" src="https://user-images.githubusercontent.com/5090034/66974729-0d309c80-f06a-11e9-947c-4c5d80901a30.png">

Can't edit [this](https://developers.redhat.com/node/212225/edit) event title from *DevNation Live: Build distributed containers* to *DevNation Tech Talk: Build distributed containers*

Can't edit [this](https://developers.redhat.com/node/212765/edit) event title from *DevNation Live: Future-proof monolithic apps* to *DevNation Tech Talk: Future-proof monolithic apps*

**Comment by joeschram** [comment]
Note that on both of the above event nodes, I have truncated the titles to fit the 45char limit. After this field is edited in Drupal to accept 55 (or more!) characters, please fix the display titles to the text strings included in the original issue description above. Thank you!

**Comment by rogeralloymagnetic** [comment]
PR: https://github.com/redhat-developer/developers.redhat.com/pull/3315

Added this content ticket to take care of the title changes once this code change is merged.
