### ISSUE TITLE
Video Hero title slides under embedded Video player on mobile viewport

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3280]
Check out the screenshots below. See it in action on the [Istio](https://developers.redhat.com/topics/service-mesh/) and [Kubernetes](https://developers.redhat.com/topics/kubernetes/) topic pages.

**Comment by joeschram** [comment]
<img width="701" alt="Screen Shot 2019-10-17 at 12 08 24 AM" src="https://user-images.githubusercontent.com/5090034/66977114-92b84a80-f072-11e9-89cf-6e321a8be627.png">

<img width="742" alt="Screen Shot 2019-10-17 at 12 10 29 AM" src="https://user-images.githubusercontent.com/5090034/66977120-964bd180-f072-11e9-8f40-ddca120e6096.png">

**Comment by staceymosier** [comment]
I cannot recreate this, and the latest activity on this thread suggests that it was fixed. Closing out.
