### ISSUE TITLE
JumpNav is gone from all mobile viewports narrower than ~480px

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3281]
- Open any page with the JumpNav assembly (like the [Containers topic page](https://developers.redhat.com/topics/containers/)) 
- Inspect and use a mobile viewport
- Resize window or change view to narrower than ~480px 

![2019-10-17 00 25 16](https://user-images.githubusercontent.com/5090034/66977627-a9f83780-f074-11e9-933c-cbed81a73664.gif)

**Comment by jordanpagewhite** [comment]
@gdoyle1 Am I correct in thinking that this is working as UX intends it to?

**Comment by jordanpagewhite** [comment]
Marking blocked until we confirm the expected functionality with UX. Pinged Gina in comment above.

**Comment by gdoyle1** [comment]
@jordanpagewhite you're right but I created an issue to reference ux designs in the front-end repo here: https://github.com/redhat-developer/rhd-frontend/issues/375

**Comment by gdoyle1** [comment]
Sorry didn't mean to close

**Comment by jordanpagewhite** [comment]
Closing per Slack conversation with @gdoyle1 spacing changes to jump-to-nav will be tracked here; https://github.com/redhat-developer/rhd-frontend/issues/375
