### ISSUE TITLE
(3) Title padding for assemblies is inconsistent

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-developer/developers.redhat.com#3291]
Estimate: 3

I noticed in [/topics/service-mesh/](https://developers.redhat.com/topics/service-mesh/) page that  the bottom padding for the assembly title is inconsistent. 

On rick text assemblies, the bottom padding is 16px (this is correct):
<img width="941" alt="Screen Shot 2019-10-17 at 9 46 22 AM" src="https://user-images.githubusercontent.com/16257540/67031155-cc667100-f0c5-11e9-8364-0efce6ef4c42.png">

On assemblies with cards, the bottom padding is 24px for titles:
<img width="988" alt="Screen Shot 2019-10-17 at 9 46 08 AM" src="https://user-images.githubusercontent.com/16257540/67031197-dc7e5080-f0c5-11e9-9b7b-26cf1bce588b.png">

Let's update it to 16px throughout all assemblies.

### Acceptance Criteria

- All header elements of similar weight render exactly the same way across the site. This could include  h2, h2.pf-c-title, etc.
- Existing header elements in WYSIWYG are styled appropriately h1,h2,h3, ... no classes

**Comment by jordanpagewhite** [comment]
Duplicates: https://github.com/redhat-developer/developers.redhat.com/issues/3290
