### ISSUE TITLE
DNL Austin - registration CTA text is wrong

### ISSUE THREAD

**Issue by svalverdetwiggs** [redhat-developer/developers.redhat.com#3297]
The CTA on [/devnationlive-austin](https://developers.redhat.com/devnationlive-austin/) is "Learn more", when the CTA text is Register.

**Comment by sjcox-rh** [comment]
@svalverdetwiggs saw that the page was updated so this is no longer an issue and all seems to be working. There is a PR waiting to be merged to address the bug you caught.
