### ISSUE TITLE
Update Utility Footer to match RH.com

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-developer/developers.redhat.com#3299]
**Estimate: 2**
Roger: I bumped the estimate up because there was a JS component to the Cookie Preferences link that wasn't accounted for in the original scoping.

There are a couple updates that need to be made to our sites utility footer to match .com.

Here is what it needs to look like:
![image](https://user-images.githubusercontent.com/16257540/67314106-fef2de00-f4b8-11e9-8358-7ade7341a993.png)

Changes that need to be made:
- Update to the new Summit logo found here (trying to hunt down logo file, will attach here when i find it)
- Add "Cookie Preferences" link.

**Comment by jordanpagewhite** [comment]
@sjcox-rh 

* Reminder to provide the new summit logo
* What interaction/where do you want to the Cookie Preferences link to direct users?
* I cannot see that `*We've updated our Privacy Statement...` line on .com. Where should the link in that statement direct users?

**Comment by sjcox-rh** [comment]
@jordanpagewhite 

Here is the new Summit logo.

<img width="434" alt="Logo-Red_Hat-Summit-A-Standard-RGB" src="https://user-images.githubusercontent.com/16257540/68150278-3d928a80-fef4-11e9-9ad9-935eb500aaf8.png">

As for the link, I also can no longer see it. I believe it's the same as the privacy statement link, but let me confirm.

**Comment by rogeralloymagnetic** [comment]
PR: https://github.com/redhat-developer/developers.redhat.com/pull/3393
