### ISSUE TITLE
Declare <scripts>s in html.html.twig in libraries

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3307]

**Comment by rogeralloymagnetic** [comment]
PR: https://github.com/redhat-developer/developers.redhat.com/pull/3350

@jordanpagewhite I've moved three of the largest offenders, but I'm not sure if we need to or should move all of the rest that are using variable logic from twig. I figured I'd push what I've got and we can discuss.
