### ISSUE TITLE
Investigate requirements to remove rhdp theme

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3309]
### Acceptance Criteria

- If reasonably feasible, ticket(s) are created that ultimately contain the acceptance criteria/steps required to entirely remove the `rhdp` theme while maintaining all of the FE styles, scripts and functionality that we require currently from the `rhdp` theme to support our old, paragraphs-based product pages

**Comment by robpblake** [comment]
@jordanpagewhite Is v1 of this to simply move what we need into `rhdp2` theme?
