### ISSUE TITLE
(5) Replace current alert styling with patternfly inline alerts

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/developers.redhat.com#3314]
**Estimate:** 5

In general, on pages where we use alerts (these are normally info alert types), we need to use patternfly inline alerts as replacements - documentation of code here https://www.patternfly.org/v4/documentation/core/components/alert#inline-alert-variations. 

Closely related to this issue #3313

**Comment by gdoyle1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redesign Media Download Confirmation Page](https://trello.com/c/MZQt2755/697-redesign-media-download-confirmation-page)

**Comment by mindreeper2420** [comment]
Marvel reference: https://marvelapp.com/6aeh0di/screen/62798969

**Comment by mindreeper2420** [comment]
Closed via PR. Additional issues created related to updating icons and the Download alert.
