### ISSUE TITLE
Update 2 event titles once #3277 is merged

### ISSUE THREAD

**Issue by rogeralloymagnetic** [redhat-developer/developers.redhat.com#3316]
Update [this](https://developers.redhat.com/node/212225/edit) event title from DevNation Live: Build distributed containers to DevNation Tech Talk: Build distributed containers

Update [this](https://developers.redhat.com/node/212765/edit) event title from DevNation Live: Future-proof monolithic apps to DevNation Tech Talk: Future-proof monolithic apps

**Comment by jordanpagewhite** [comment]
I have updated these two node titles. I will see if someone is available to review my work and then we can close it.

**Comment by rogeralloymagnetic** [comment]
@jordanpagewhite looks good, closing this issue.

**Comment by jordanpagewhite** [comment]
Thank you
