### ISSUE TITLE
Unpublished katacodas appear like the unpublished product pages

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3338]
Estimate: 2

### Acceptance criteria

- Draft state katacoda individual lessons are not displayed for unprivileged users on /courses or /courses/[course-slug], but will display for users with access to 'view unpublished content'

**Comment by jordanpagewhite** [comment]
Need more info

**Comment by jordanpagewhite** [comment]
Katacoda individual lessons (draft state) are being aggregated on https://localhost/courses/

**Comment by joeschram** [comment]
Documentation for [How to publish a katacoda on RHD](https://docs.google.com/document/d/1rOp2lv_b2ZbqJiXU33zW9LC82sSyf2X7EMHp_8Gzua0/edit)

**Comment by jordanpagewhite** [comment]
I tried getting unpublished Katacoda content (courses and individual lessons) to appear for unprivileged users, but I could not seem to replicate this bug. The All Courses View filters by 'Published (=Yes)', and the Katacoda Course nodes render the Katacoda Individual Lesson entity reference(s), which _should_ respect publishing status of those referenced nodes.

I also reviewed the steps in the `How to publish a katacoda on RHD` Google doc (linked in the comment above). Those steps advise publishing each node, which would of course result in them being available to all users. However, if you just published those nodes in a Draft state, you should see that they are not available to unprivileged users.

**Comment by jordanpagewhite** [comment]
### Steps to verify

#### Created unpublished Katacoda Individual lesson

Go here: https://localhost/node/add/katacoda_individual_lesson
Do this: Create a Katacoda Individual Lesson by filling out the necessary, required fields and saving the form, ensuring you Save as Draft state

#### Attach unpublished Katacoda Individual Lesson to published Katacoda Course

Go here (example): https://localhost/courses/modern-app-dev/edit?destination=/admin/content
Do this:

- Reference your unpublished Katacoda Individual Lesson in the 'KATACODA COURSE LESSONS' field
- Save the form

You should see this:

<img width="1453" alt="Screen Shot 2019-11-21 at 1 46 12 PM" src="https://user-images.githubusercontent.com/7155034/69379426-4e1d6180-0c65-11ea-977b-2e09a2604261.png">

**Comment by jordanpagewhite** [comment]
@joeschram I am going to close this issue as 'Could not replicate', for now. I would be happy to reopen the issue though if you (or anyone) can define the steps needed to replicate the issue. I've outlined a few attempts here to recreate the issue, and could not. I also followed the linked Google Doc. Please let me know what you think. Thanks.
