### ISSUE TITLE
Modify our katacoda ingestion to that we can consume RHEL8 katacodas from https://lab.redhat.com/

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/developers.redhat.com#3344]

**Comment by jordanpagewhite** [comment]
@gdoyle1 Can you elaborate on what is preventing us from accomplishing your goal(s) given our current tools and/or further explain how/what you want to accomplish in consuming katacodas from lab.redhat.com?

**Comment by gdoyle1** [comment]
@jordanpagewhite I actually have no idea what this issue is about - @sjcox-rh @joeschram did one of you create this?

**Comment by sjcox-rh** [comment]
@gdoyle1 I believe @joeschram created this issue. @jordanpagewhite are we not able to pull katacodas to developer from lab.redhat.com now?

**Comment by joeschram** [comment]
Guess what? Amazingly, this appears to already work as-is!
