### ISSUE TITLE
Jump Nav spacing fix

### ISSUE THREAD

**Issue by sjcox-rh** [redhat-developer/developers.redhat.com#3346]
**Description**
On certain pages that use the jump nav assembly, the top padding is removed.

**To Reproduce**
1. Go to /topics/event-driven/
2. Scroll down to jump nav
4. See lack of top padding on nav items

**Expected behavior**
The jump nav items should be centered vertically within the blue jump nav area.

**Screenshots/GIFs**
<img width="1312" alt="Screen Shot 2019-11-04 at 11 07 21 AM" src="https://user-images.githubusercontent.com/16257540/68150111-e7bde280-fef3-11e9-9402-d3e79a58fc09.png">

**Comment by alistairmc** [comment]
@sjcox-rh this was fixed in a previous ticket, the build in live has the fix now.

Please re-test and if ok close

**Comment by sjcox-rh** [comment]
@alistairmc thanks alistair, just checked and it's fixed. Closing now.
