### ISSUE TITLE
Need a clear way to communicate services outages to users

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3355]
**Is your feature request related to a problem? Please describe.**
Kind of. As a developer, devops or anyone responsible for the site (could be someone who does not touch code), I need to be able to alert site users of an outage with a service that we rely on. For example, if Keycloak has an outage, I need a way to clearly tell site users that authentication will not work, so gated content/downloads will not work.

**Describe a solution you'd like**
It seems like a site-wide banner component, that could display below the masthead but above content and that could be configured by any of our trusted users, could clearly communicate these service outages to our users.

**Additional context**

**Comment by jordanpagewhite** [comment]
As part of this issue, we should investigate if a site-wide alert/banner web component exists in our codebase and determine the extent that we can re-use that component for this use case.

**Comment by robpblake** [comment]
We currently display outages based on failures of our New Relic synthetics via status.redhat.com. Could we do something that occasionally polls for our status on status.redhat.com and if we're showing any form of service degradation, presents a small banner to users to let them know that not everything might be working.
