### ISSUE TITLE
Strip the old theme styling from tables

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/developers.redhat.com#3365]
**Description**
Tables are still pulling in old theme styling. Specifically the table headers are getting a black background. I think some text styling is still being pulled in as well.

**To Reproduce**
1. Go to developers.redhat.com/devnationlive-austin
2. Scroll down to the schedule table

**Expected behavior**
Table header row should not have a black background. It should have the same styling (with our font of course) as the patternfly table.

**Screenshots/GIFs**
See the pf documentation for more on this: https://pf4.patternfly.org/documentation/core/components/table.

**Comment by staceymosier** [comment]
This has been moved to JIRA [RHDX-121](https://projects.engineering.redhat.com/browse/RHDX-121)
