### ISSUE TITLE
Scroll to top box needs visual meaning

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3371]
There is a gray box that appears, floating, on the right side of the page (desktop viewport) as you scroll down. I think that we could use an icon or some meaning visual component(s) to inform a user of the purpose of this gray box.

<img width="1062" alt="Screen Shot 2019-11-14 at 5 12 08 PM" src="https://user-images.githubusercontent.com/7155034/68900597-2fb5e400-0702-11ea-9505-e6c5e86ea01c.png">

### Acceptance Criteria

- There is some visual component(s)/icon(s) that inform users of the purpose of this gray box

**Comment by alistairmc** [comment]
Moved to https://projects.engineering.redhat.com/browse/RHDX-127
