### ISSUE TITLE
(3) Create "Compact Dynamic Article List" assembly

### ISSUE THREAD

**Issue by fearlsgroove** [redhat-developer/developers.redhat.com#3401]
**Estimate:** 3

Create a new assembly type to show lists of articles in a compact format. See the left section in this mock:
https://marvelapp.com/c6c454h/screen/59506431

* New frontend component for compact article list matching mock
* Create a new assembly type "Compact Dynamic Article List" showing drupal articles and wordpress nodes. 
* Allow filtering on wordpress category and drupal terms. Reuse functionality from "dynamic list with disqus" type.
* Show disqus comment counts as applicable

Note: This implements the compact article list assembly, but not the column layout for the homepage.

**Comment by rogeralloymagnetic** [comment]
Initial WIP PR: https://github.com/redhat-developer/developers.redhat.com/pull/3411

**Comment by rogeralloymagnetic** [comment]
Pulled out Disqus comment count to this ticket: https://github.com/redhat-developer/developers.redhat.com/issues/3434
