### ISSUE TITLE
(3) List view assembly for Connectors content type

### ISSUE THREAD

**Issue by joeschram** [redhat-developer/developers.redhat.com#3405]
**Estimate:** 3

Content at this page:

https://developers.redhat.com/products/fuse/connectors

pulls from the Connectors content type in Drupal.

This page (and the whole Fuse product page triptych) is being converted to the new product page design.

What we need is a net-new assembly that uses the existing List View design, displaying the value in the `Title` field as a hyperlink to the URL in the `Connector Details URL` field, followed by the text in the `Connector Short Description` field as the link description.

![Screen Shot 2019-11-25 at 10 55 32 AM](https://user-images.githubusercontent.com/5090034/69556151-449c3e00-0f72-11ea-9a9c-524b96c5c727.png)

**Comment by gdoyle1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fuse connectors list view](https://trello.com/c/6DzbDson/724-fuse-connectors-list-view)

**Comment by gdoyle1** [comment]
https://marvelapp.com/a078f73 - this is using the patternfly list component. Let me know if you need more design specs for this
