### ISSUE TITLE
(3) Implement layout assembly for homepage

### ISSUE THREAD

**Issue by fearlsgroove** [redhat-developer/developers.redhat.com#3407]
**Estimate:** 3

**Is your feature request related to a problem? Please describe.**
Create a new layout assembly to accommodate the grid that appears in this screen:
https://marvelapp.com/c6c454h/screen/59506431/handoff

The grid should have left and right columns that align with the proportions shown in the mock.

**Describe a solution you'd like**
* A new assembly type with 2 fields, left column and right column, entity reference revisions to attach assemblies, allow multiple
* the left assembly should allow rich text and the compact dynamic article list.
* the right assembly should allow rich text and most other top-level eligible assembly types. Test the different types to see how they perform in the space.
* Show mobile first -- the right column should appear above the left (narrow) column

**Comment by joeschram** [comment]
Content for the assembly [tracked in this doc](https://docs.google.com/document/d/1omSrY4WzW8fpRlOJ_Vl2a4ZeCau0ANsRIS7u-lpsyPc/edit).

**Comment by rogeralloymagnetic** [comment]
Initial WIP PR: https://github.com/redhat-developer/developers.redhat.com/pull/3411
