### ISSUE TITLE
New Cookie Banner does not disappear when the user accepts the cookies

### ISSUE THREAD

**Issue by robpblake** [redhat-developer/developers.redhat.com#3409]
**Description**

We have a new cookie banner from #3299 When I visit the site and accept the cookie terms, the banner does not disappear and I'm left with an unusable website. Instead I have to refresh the page in order to continue using the site.

Additionally the styling of the cookie banner is broken with extra space underneath

**To Reproduce**

1. Visit developers.redhat.com in incognito mode
2. Accept the terms on the cookie banner
3. Note that the cookie banner does not disappear
4. Refresh the page and note that the cookie banner is now accepted

**Expected behavior**

* The cookie banner styling should match as expected
* The cookie banner should disappear completely when the user has accepted the cookies

**Screenshots/GIFs**

<img width="926" alt="Screenshot 2019-11-26 at 14 12 10" src="https://user-images.githubusercontent.com/1170393/69640753-d2515980-1056-11ea-88ec-dc2524121c36.png">

<img width="1117" alt="Screenshot 2019-11-26 at 14 01 35" src="https://user-images.githubusercontent.com/1170393/69640613-8acacd80-1056-11ea-9b91-4934885efb9f.png">

**Comment by jordanpagewhite** [comment]
@robpblake I believe that this was closed by #3410 , correct?

**Comment by jordanpagewhite** [comment]
Well, actually, we could/should use this issue for the re-implementation of the cookie banner as we do need it long-term. In the meantime, it has been temporarily 'resolved' by being removed.

**Comment by alistairmc** [comment]
@jordanpagewhite there seems to be a working cookie banner is this ticket still valid?
