### ISSUE TITLE
List items get a different font style

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/developers.redhat.com#3420]
**Description**
When text is formatted in a list (bulleted or numbered), the font styles are overridden. Usually only happens with standard text size (16px).

**To Reproduce**
1. Go to 'developers.redhat.com/products/fuse/hello-world-fuse-tooling'
2. Scroll down to any of the bulleted items
4. See the different font style applied

**Expected behavior**
The font style should match whatever typography styles are being used. So for list items that are created using the standard text style, it should be formatted as red hat text regular 16px.

**Comment by alistairmc** [comment]
moved to https://projects.engineering.redhat.com/browse/RHDX-126
