### ISSUE TITLE
Code snippet assembly doesn't work

### ISSUE THREAD

**Issue by gdoyle1** [redhat-developer/developers.redhat.com#3421]
**Description**
I tried inserting a code snippet assembly into an article and it did not appear on the article itself. The assembly functionality worked and allowed me to insert the information though.

**To Reproduce**
1. Go to any article in drupal
2. Add new code snippet assembly
3. Draft or publish the article
4. Code snippet will not appear

**Expected behavior**
Code snippet should appear as seen in the front-end repo.

**Comment by staceymosier** [comment]
Hi @gdoyle1,  would it be possible to connect with you and have a screenshare on how to recreate this issue?

**Comment by staceymosier** [comment]
@jordanpagewhite   Gina mentioned this issue might be related to another one, https://github.com/redhat-developer/developers.redhat.com/pull/3259 

I don't see any option to edit this issue to link them.

**Comment by staceymosier** [comment]
@gdoyle1   I think you are right,  the issue #3259 is the same. I used the pending changes from that ticket and the code snippet assembly displays, but the visual style issue that you mentioned in the other issue is still happening.

This one can be closed as a duplicate. Thanks!

**Comment by staceymosier** [comment]
@gdoyle1 

I have moved this issue to [RHDX-101](https://projects.engineering.redhat.com/projects/RHDX/issues/RHDX-101) and will start working on it now.
