### ISSUE TITLE
Update 'More like this' section to use new styles/designs

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3423]
**Is your feature request related to a problem? Please describe.**

Yes, the 'More like this' section on Video pages looks distinctly different than similar components across the site. For example, the cards in that section do not use our standard card styles nor card grid styles/markup. The header also does not match our standard markup/style.

Example Video Resource nodes:

https://localhost/videos/youtube/FC3jSKgTNK0/
https://localhost/videos/youtube/Qcys7fKSzB0/

Filepath to template: ./drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--video-resource--full.html.twig

### Current - mobile viewport
<img width="498" alt="Screen Shot 2019-12-03 at 9 48 01 AM" src="https://user-images.githubusercontent.com/7155034/70075627-04f8d600-15b2-11ea-81f6-d1426ce18170.png">

### Current - desktop viewport
<img width="1563" alt="Screen Shot 2019-12-03 at 9 47 51 AM" src="https://user-images.githubusercontent.com/7155034/70075630-04f8d600-15b2-11ea-8b73-7d9f1977c4ec.png">

**Describe a solution you'd like**

### Proposed - mobile viewport
<img width="608" alt="Screen Shot 2019-12-03 at 9 41 37 AM" src="https://user-images.githubusercontent.com/7155034/70075575-eeeb1580-15b1-11ea-924b-1d64145f4158.png">

### Proposed - desktop viewport
<img width="1476" alt="Screen Shot 2019-12-03 at 9 40 57 AM" src="https://user-images.githubusercontent.com/7155034/70075573-eeeb1580-15b1-11ea-85a3-09fef8b7b64b.png">

### Proposed - markup
<img width="1290" alt="Screen Shot 2019-12-03 at 9 42 11 AM" src="https://user-images.githubusercontent.com/7155034/70075576-ef83ac00-15b1-11ea-8f7a-276e8d3da7a3.png">

**Additional context**

n/a

**Stakeholders**

@sjcox-rh 
@jordanpagewhite

**Comment by staceymosier** [comment]
@jordanpagewhite   I looked into this and the plan I have is to copy the related content treatment from node--article--full.html.twig to the node--video-resource--full.html.twig.   This includes changing the display settings for Video:  Default (full) and Card.   So before I do that, I will check the config files if video displayed as card is already used elsewhere.  

I'm not certain that the article/video related content can use the card twig component that the assemblies templates are referencing,  but if I should follow that  route, please let me know.

**Comment by staceymosier** [comment]
The card  markup has to be updated in related-content.js file and the grid wrapper added to the video full template.

Other than that, the 'field_related_content' is also exposed under the 'more like this', however for the video content type, this field has only been used on 2 nodes in 2017

nid **title** FROM_UNIXTIME(a.created) field_related_content_target_id 
173485 **Why you’re going to fail running Java on Docker DevNation Live** 2017-12-07 18:55:46 204155
173425 **Going Reactive with Java DevNation Live** 2017-12-07 18:46:50 39055

**Comment by staceymosier** [comment]
This is now in JIRA, [RHDX-93](https://projects.engineering.redhat.com/browse/RHDX-93)
