### ISSUE TITLE
iFrame heights not correct when embedding YouTube and other content

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3424]
**Description**

Example page: https://developers.redhat.com/articles/istio-service-mesh-intro/

On this page, you can see that the height of the YouTube and Slidr iframes are not correct. They are too short, causing the content to cut off. You will see if you inspect the iframe and uncomment the `height: auto`:

<img width="1568" alt="Screen Shot 2019-12-03 at 2 06 49 PM" src="https://user-images.githubusercontent.com/7155034/70093899-36839880-15d6-11ea-952c-0643d83b71ed.png">

That the iframes will have the proper height:

<img width="1490" alt="Screen Shot 2019-12-03 at 2 07 40 PM" src="https://user-images.githubusercontent.com/7155034/70093928-49966880-15d6-11ea-9013-3d19c0aa898e.png">

**Expected behavior**
As an editor, I want to be able to embed YouTube and other iframe content without any of the content being cut off.

**Comment by alistairmc** [comment]
moved to jira https://projects.engineering.redhat.com/browse/RHDX-108
