### ISSUE TITLE
Convert related-content.js to a Drupal behavior

### ISSUE THREAD

**Issue by jordanpagewhite** [redhat-developer/developers.redhat.com#3427]
**Is your feature request related to a problem? Please describe.**

Yes, this script is not implemented as a Drupal behavior, so there are certain hypothetical loading contexts in which it will fail to load. The Related Content 'section' is not used in any of those ways now, but examples could be if it were implemented within a View with AJAX reloading functionality of any sort (filter, pager, etc.) or if it became content that was loaded within an administration UI via AJAX.

**Describe a solution you'd like**

File path: web/themes/custom/rhdp2/rhd-frontend/src/scripts/js/2018/related-content.js

Rewrite the file as a Drupal behavior and move it into ./web/themes/custom/rhdp2/js/ directory. I do not think that there is any reason to load this in the `rhd-frontend` project since it is not used in the Hugo site/styleguide, and it could just be clearly designated as a Drupal behavior/Drupal-specific JS file in this way.

**Comment by staceymosier** [comment]
This is related: #3423

**Comment by staceymosier** [comment]
This is now in JIRA, [RHDX-93](https://projects.engineering.redhat.com/browse/RHDX-93)

**Comment by jordanpagewhite** [comment]
Thanks!
