### ISSUE TITLE
Redirect for /cheat-sheets/ does not work with query param from WP blogs

### ISSUE THREAD

**Issue by staceymosier** [redhat-developer/developers.redhat.com#3432]
**Description**
Several blog posts end with a text snippet that links to 
https://developers.redhat.com/cheat-sheets/?sc_cid=7013a000002Cv4JAAS

This goes to a 404. Without the ?sc_cid query parameter, the redirect works.

**To Reproduce**
1. Go to blog post [Plumbing Kubernetes CI/CD with Tekton](https://developers.redhat.com/blog/2019/11/12/plumbing-kubernetes-ci-cd-with-tekton/)
2. Scroll down to Learn more, and find the recurring text: Join Red Hat Developer and get access to handy cheat sheets, free books, and product downloads.
3. Click on 'cheat sheets' link.
4. See error/issue

**Expected behavior**
The link https://developers.redhat.com/cheat-sheets/?sc_cid=7013a000002Cv4OAAS has the same redirect behavior as https://developers.redhat.com/cheat-sheets/

You should be able to:
1. Go to blog post [Plumbing Kubernetes CI/CD with Tekton]
3. Scroll down to Learn more
4. You should see this: The hyperlink on cheat sheets works.

**Screenshots/GIFs**
<img width="1914" alt="Screen Shot 2019-12-06 at 2 25 33 PM" src="https://user-images.githubusercontent.com/19995927/70350241-56b09300-1834-11ea-9dd7-580dde81a5e0.png">

**Additional context**
Message from @joeschram 

> Here's why that is happening:
> That old URL is a redirect to a search query, that's how we used to offer the list of cheat sheets. Since that link was added to the bottom of all articles, we've made this page to do that job: https://developers.redhat.com/cheatsheets/
> So the fix is, that article template in Wordpress needs to switch the link from:
> https://developers.redhat.com/cheat-sheets/?sc_cid=7013a000002Cv4JAAS
> to https://developers.redhat.com/cheatsheets?sc_cid=7013a000002Cv4JAAS
> 
> The string after the ? is the salesforce offer ID that we use to track that someone is browsing cheat sheets came from an article—very important info.

**Comment by alistairmc** [comment]
Moved to https://projects.engineering.redhat.com/browse/RHDX-125
