### ISSUE TITLE
Add Disqus comment count to compact_dynamic_article_list assembly

### ISSUE THREAD

**Issue by rogeralloymagnetic** [redhat-developer/developers.redhat.com#3434]
**Is your feature request related to a problem? Please describe.**
Continuation of implementation from this ticket: https://github.com/redhat-developer/developers.redhat.com/issues/3401

**Describe a solution you'd like**
Add comment count to article title to match design: https://marvelapp.com/c6c454h/screen/59506431/

**Additional context**
1. I've had issues getting Disqus to run locally.
2. There isn't an implementation of the comment count yet, so this is net-new work that wasn't pointed as such from the previous ticket.

**Comment by alistairmc** [comment]
Moved to https://projects.engineering.redhat.com/browse/RHDX-124
