### ISSUE TITLE
Footer Category carets are incorrect on desktop views

### ISSUE THREAD

**Issue by mindreeper2420** [redhat-developer/developers.redhat.com#3436]
Estimate: 1

**Description**
On a desktop viewport, the expansion carets for the footer categories appear on desktop viewports, when they should only appear on mobile viewports. On the mobile viewport, they should be white (as they currently are).

**To Reproduce**
1. Go to any page with a footer
2. View the footer on a desktop viewport - carets appear, are incorrect icon, and are black
3. View the footer on a mobile viewport - carets appear, are correct icon, and are white

**Expected behavior**
The Category carets used for expansion should only appear on mobile viewports and be white.

**Screenshots/GIFs**
_Desktop Viewport_
<img width="1049" alt="Screen Shot 2019-12-09 at 10 27 12 AM" src="https://user-images.githubusercontent.com/4032718/70448792-dfb30e80-1a6e-11ea-94a4-291aa19a1e59.png">

_Mobile Viewport_
<img width="404" alt="Screen Shot 2019-12-09 at 10 27 21 AM" src="https://user-images.githubusercontent.com/4032718/70448818-e5a8ef80-1a6e-11ea-8dc2-fc695dd52bdb.png">

**Comment by alistairmc** [comment]
@mindreeper2420 just picked this up I am unable to reproduce this issue on either my local build or the live site, what browser were you seeing this on?

**Comment by mindreeper2420** [comment]
@alistairmc I'm using Firefox 71 on macOS on the live site. I also checked and verified that it appears on Safari and Chrome as well. You might have to turn up your contrast/brightness to see it.

**Comment by alistairmc** [comment]
@mindreeper2420 I see it thanks, it's a completely different element to the mobile one I will sort that out thanks for the update.
