### ISSUE TITLE
Kestrel dotnet 3.1 File Upload Fails for file size above 200KB  

### ISSUE THREAD

**Issue by boukisge** [redhat-developer/developers.redhat.com#3599]
We are experiencing an issue with dotnet 3,1 application using kestrel running in openshift 4.4 on-prem.
File upload via REST API post fails for file size > 200KB . It works for file size under 200kB in the container

It works fine locally running same code in MS Visual Studio 201

Actual behaviour inside the container: "Read-only file system" exception at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsTContext for file uploads > 200KB
file size under 200kb inside the container it works fine

**Comment by audioroger** [comment]
Hi @boukisge this project is no longer active/monitored and was only ever used for the actual website code for developers.redhat.com. It sounds like your issue is more related to a specific product and should be directed to another support channel.
