### ISSUE TITLE
Please Update My Name on the Devoxx Microsite

### ISSUE THREAD

**Issue by myfear** [redhat-developer/developers.redhat.com#539]
http://developers.redhat.com/events/devoxx/2015/

"Meet Marcus Eisle, author of Modern Java EE Pattern Designs" should be:

"Meet Markus Eisele, author of Modern Java EE Design Patterns"

I also would like to see the book cover and a link to the promotional site: http://developers.redhat.com/promotions/distributed-javaee-architecture/

**Comment by adelasofia** [comment]
Hi @myfear I've created a Jira for this issue, since we don't really use Github issues. You can track it here: https://issues.jboss.org/browse/RHD-1001 :smiley:
