### ISSUE TITLE
README.md update data load portion of Set up

### ISSUE THREAD

**Issue by rctrh** [redhat-developer/developers.redhat.com#989]
In the Set up section of README.md

* There should be a mention that the listed data files are in a private repo. 
* The instructions cover 2 tar files, but I also received two zip files,`searchisko_2.sql.zip` and `searchisko.sql.zip`.  Do these also go in ` _docker/mysql`?

Current:
```
### Set up
Download the [MySQL data dump](https://github.com/redhat-developer/searchisko-docker/raw/master/searchisko/searchisko_mysql_data.tar.gz) and copy to `_docker/mysql/searchisko_mysql_data.tar.gz`.

Download the [ElasticSearch data dump](https://github.com/redhat-developer/searchisko-docker/raw/master/searchisko/searchisko_es_data.tar.gz) and copy to `_docker/searchisko/searchisko_es_data.tar.gz`.
```

**Comment by LightGuard** [comment]
No follow the README, the others I think are old and no longer used.
